
image: giomasce/testenv

variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: "3"

before_script:
  - cat /proc/cpuinfo
  - cat /proc/meminfo
  - apt-get update
  - apt-get install -y --no-upgrade eatmydata

stages:
  - test

test:
  stage: test
  script:
    - eatmydata apt-get install -y --no-upgrade build-essential libz3-dev libmicrohttpd-dev qt5-default libboost-all-dev node-typescript binutils-dev pkg-config wget git
    - wget -q -O resources/set.mm https://github.com/metamath/set.mm/raw/develop/set.mm
    - git clone https://github.com/giomasce/metamath-test.git resources/metamath-test
    - tsc -p resources/static/ts
    - sed -i -e 's|^USE_QT = .*$|USE_QT = true|' mmpp.pro
    - sed -i -e 's|^USE_MICROHTTPD = .*$|USE_MICROHTTPD = true|' mmpp.pro
    - sed -i -e 's|^USE_BEAST = .*$|USE_BEAST = true|' mmpp.pro
    - sed -i -e 's|^USE_Z3 = .*$|USE_Z3 = true|' mmpp.pro
    - mkdir build
    - cd build
    - qmake ..
    - make -j $(nproc)
    - time ./mmpp test
    - time ./mmpp verify_all
